---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
type: opaque
data:
  password: cm9vdA==
---

apiVersion: v1
kind: Pod
metadata:
  name: httpd
spec:
  containers:
  - name: httpd
    image: httpd
    env:
      - name: DEMO
        valueFrom:
          secretKeyRef:
            key: password
            name: mysql-root-password
    ports:
      - containerPort: 80

