apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-1
spec:
  replicas: 4
  selector:
    app: nginx
    ver: 1.1
  template:
    metadata:
     lables: 
       app: nginx
       ver: 1.1
    spec:
      containers:
      - name: rc-container
        image: nginx
        ports:
        - containerport: 80
